#!/bin/bash
# install_logger.sh — Install skill usage logging hooks into a target project
#
# Usage: ./scripts/install_logger.sh <target-project-path>
#
# This adds hooks to the target project's .claude/settings.local.json that:
# 1. Capture every user prompt (UserPromptSubmit)
# 2. Log which skill/agent was triggered (SubagentStop + PostToolUse)
#
# Logs are written to: <target-project>/.claude/skill_usage_log.jsonl
# Review logs with: ./scripts/promote_cases.py <target-project>/.claude/skill_usage_log.jsonl

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK_SCRIPT="$SCRIPT_DIR/skill_logger_hook.sh"

TARGET="${1:-}"

if [ -z "$TARGET" ]; then
  echo "Usage: $0 <target-project-path>" >&2
  echo "" >&2
  echo "Installs skill usage logging hooks into the target project." >&2
  echo "Logs go to <target>/.claude/skill_usage_log.jsonl" >&2
  exit 1
fi

TARGET=$(cd "$TARGET" && pwd)

if [ ! -d "$TARGET" ]; then
  echo "Error: $TARGET is not a directory" >&2
  exit 1
fi

# Create .claude directory if needed
mkdir -p "$TARGET/.claude/hooks"

# Copy the hook script
cp "$HOOK_SCRIPT" "$TARGET/.claude/hooks/skill_logger_hook.sh"
chmod +x "$TARGET/.claude/hooks/skill_logger_hook.sh"

# Create or update settings.local.json (project-local, gitignored)
SETTINGS="$TARGET/.claude/settings.local.json"

if [ -f "$SETTINGS" ]; then
  # Merge hooks into existing settings
  EXISTING=$(cat "$SETTINGS")
else
  EXISTING="{}"
fi

# Write the hooks configuration
python3 -c "
import json

settings = json.loads('''$EXISTING''')

if 'hooks' not in settings:
    settings['hooks'] = {}

hooks = settings['hooks']

# UserPromptSubmit — capture user prompt
hooks['UserPromptSubmit'] = [{
    'matcher': '',
    'hooks': [{
        'type': 'command',
        'command': '.claude/hooks/skill_logger_hook.sh'
    }]
}]

# SubagentStop — capture which subagent finished
hooks['SubagentStop'] = [{
    'matcher': '',
    'hooks': [{
        'type': 'command',
        'command': '.claude/hooks/skill_logger_hook.sh'
    }]
}]

# PostToolUse — capture Skill/Agent tool calls
hooks['PostToolUse'] = hooks.get('PostToolUse', [])

# Add skill logger if not already present
skill_logger_present = any(
    any(h.get('command', '').endswith('skill_logger_hook.sh') for h in entry.get('hooks', []))
    for entry in hooks['PostToolUse']
)
if not skill_logger_present:
    hooks['PostToolUse'].append({
        'matcher': 'Agent|Skill',
        'hooks': [{
            'type': 'command',
            'command': '.claude/hooks/skill_logger_hook.sh'
        }]
    })

with open('$SETTINGS', 'w') as f:
    json.dump(settings, f, indent=2)
"

# Add log file to gitignore if not already there
GITIGNORE="$TARGET/.gitignore"
if [ -f "$GITIGNORE" ]; then
  if ! grep -q "skill_usage_log.jsonl" "$GITIGNORE" 2>/dev/null; then
    echo "" >> "$GITIGNORE"
    echo "# Skill usage logs (generated by skill logger hook)" >> "$GITIGNORE"
    echo ".claude/skill_usage_log.jsonl" >> "$GITIGNORE"
    echo ".claude/.last_prompt_*" >> "$GITIGNORE"
  fi
fi

echo "=== Skill Logger Installed ==="
echo "  Target:   $TARGET"
echo "  Hook:     $TARGET/.claude/hooks/skill_logger_hook.sh"
echo "  Settings: $TARGET/.claude/settings.local.json"
echo "  Log:      $TARGET/.claude/skill_usage_log.jsonl"
echo ""
echo "Usage:"
echo "  1. Use Claude Code normally in $TARGET"
echo "  2. Review captured cases:"
echo "     python3 $REPO_ROOT/scripts/promote_cases.py $TARGET/.claude/skill_usage_log.jsonl"
echo "  3. Promote interesting cases to eval set for optimization"
